# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

 ci:
  runs-on: ubuntu-latest
  steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5

      - name: PHPUnit Practicas Tests
        uses: php-actions/phpunit@v2
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml



  # This workflow contains a single job called "build"

 cd:
  runs-on: ubuntu-latest
  needs: ci
  steps:
    - uses: actions/checkout@v1
    - name: Docker login practica
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/pruebaciandcd:${{ github.sha }} .
        docker build -t ${{ secrets.DOCKER_USER }}/pruebaciandcd:latest .
      #- name: Tags
       # run: |
        #  docker tag back ${{ secrets.DOCKER_USER }}/pruebaciandcd:${{ github.sha }}
         # docker tag back ${{ secrets.DOCKER_USER }}/pruebaciandcd:latest
    - name: Push
      run:  |
        docker push ${{ secrets.DOCKER_USER }}/pruebaciandcd:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USER }}/pruebaciandcd:latest
